spring:
  application:
    name: say-hello-1
    profiles.active: zone1

server:
  port: 8091
  

eureka:
  client:
    lease:
      duration: 5
    prefer-same-zone-eureka: true
    region: region-1
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://127.0.0.1:8762/eureka/
    availability-zones:
      region-1: zone1,zone2
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

